=== uo68216/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"	
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es" 
	elementFormDefault="qualified" >
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="carrera" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="salida" />
				<xs:element ref="tramos" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="pais" type="xs:string" use="required" />
			<xs:attribute name="localidad" type="xs:string" use="required" />
			<xs:attribute name="longitudCircuito" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="anchuraMedia" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="0.0"/>
						<xs:fractionDigits value="4"/>
					</xs:restriction>
            	</xs:simpleType>
			</xs:attribute> 

		</xs:complexType>
	</xs:element>
	<xs:element name="carrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fecha" />
				<xs:element ref="horaInicio" />
				<xs:element ref="vueltas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />
	<xs:element name="vueltas">
		<xs:simpleType>
			<xs:restriction base="xs:nonNegativeInteger">
				<xs:maxInclusive value="200"/>
			</xs:restriction>
		</xs:simpleType>	
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="salida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:string" />
	<xs:element name="latitud" type="xs:string" />
	<xs:element name="altitud" type="xs:string" />
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sector" />
				<xs:element ref="distancia" />
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:string" />
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== uo68216/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8" ?>
<circuito xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
	nombre="Gilles Villeneuve" 
	pais="Canada" 
	localidad="Montreal" 
	longitudCircuito="4361" 
	anchuraMedia="11.968">
	<carrera>
		<fecha>2024-06-09</fecha>
		<horaInicio>20:00:00</horaInicio>
		<vueltas>70</vueltas>
	</carrera>
	<referencias>
		<referencia>https://es.wikipedia.org/wiki/Circuito_Gilles_Villeneuve</referencia>
		<referencia>https://www.racingatmosphere.net/circuitos/circuit-gilles-villeneuve/</referencia>
		<referencia>https://es.motorsport.com/f1/news/horarios-canada-formula1-como-ver-tv-2024/10618370/</referencia>
	</referencias>
	<fotos>
		<foto>multimedia\imagenes\Circuito-Vista-Aerea.jpg</foto>
		<foto>multimedia\imagenes\Circuito-Horquilla.png</foto>
		<foto>multimedia\imagenes\Circuito-Curva10.jpg</foto>
		<foto>multimedia\imagenes\Circuito-Muro-Campeones.jpg</foto>
	</fotos>
	<videos>
		<video>multimedia\videos\circuito-muro-campeones.mp4</video>
		<video>multimedia\videos\circuito-vuelta.mp4</video>
	</videos>
	<salida>
		<longitud>-73.52271782342224</longitud>
		<latitud>45.50010458094061</latitud>
		<altitud>9.584033172035035</altitud>
	</salida>
	<tramos>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">28.95</distancia>
			<longitud>-73.52264134608241</longitud>
			<latitud>45.49984978108439</latitud>
			<altitud>9.582452404304483</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">22.48</distancia>
			<longitud>-73.52260890597879</longitud>
			<latitud>45.49964893087726</latitud>
			<altitud>9.670254369317231</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">24.06</distancia>
			<longitud>-73.52258630835026</longitud>
			<latitud>45.49943315561567</latitud>
			<altitud>9.696738125058527</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">29.36</distancia>
			<longitud>-73.52258401230654</longitud>
			<latitud>45.49916912276533</latitud>
			<altitud>9.778224436150612</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">25.56</distancia>
			<longitud>-73.52260009560504</longitud>
			<latitud>45.49893957055278</latitud>
			<altitud>9.79139297086772</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">36.47</distancia>
			<longitud>-73.52264879573508</longitud>
			<latitud>45.49861335360456</latitud>
			<altitud>9.987890438656509</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">45.50</distancia>
			<longitud>-73.5227228093959</longitud>
			<latitud>45.49820743135943</latitud>
			<altitud>10.0964542419106</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">25.34</distancia>
			<longitud>-73.52276117380028</longitud>
			<latitud>45.49798109586177</latitud>
			<altitud>10.2124260637003</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">9.67</distancia>
			<longitud>-73.52277168497214</longitud>
			<latitud>45.49789447455493</latitud>
			<altitud>10.17588849091425</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">9.19</distancia>
			<longitud>-73.52274693509695</longitud>
			<latitud>45.49781366959589</latitud>
			<altitud>10.20501147836683</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">6.91</distancia>
			<longitud>-73.52269714362315</longitud>
			<latitud>45.49776226865474</latitud>
			<altitud>10.19360986920697</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">4.79</distancia>
			<longitud>-73.52264856773367</longitud>
			<latitud>45.49773588204641</latitud>
			<altitud>10.1992289403537</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">7.12</distancia>
			<longitud>-73.52256880787472</longitud>
			<latitud>45.49770457293057</latitud>
			<altitud>10.20132102143068</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">33.73</distancia>
			<longitud>-73.52217363684717</longitud>
			<latitud>45.49758085723263</latitud>
			<altitud>10.31358629041475</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">9.86</distancia>
			<longitud>-73.52206094594847</longitud>
			<latitud>45.49754065318345</latitud>
			<altitud>10.30987203060466</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.82</distancia>
			<longitud>-73.52198990446514</longitud>
			<latitud>45.49747888820899</latitud>
			<altitud>10.36302519771376</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.71</distancia>
			<longitud>-73.52195880253416</longitud>
			<latitud>45.49740368959773</latitud>
			<altitud>10.41843807607646</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">9.02</distancia>
			<longitud>-73.52196293304581</longitud>
			<latitud>45.4973226589772</latitud>
			<altitud>10.44838083247084</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.78</distancia>
			<longitud>-73.52199607660091</longitud>
			<latitud>45.49724722504228</latitud>
			<altitud>10.50458991456233</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.38</distancia>
			<longitud>-73.52205169563138</longitud>
			<latitud>45.49718276974514</latitud>
			<altitud>10.70638725081858</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.68</distancia>
			<longitud>-73.5221350441999</longitud>
			<latitud>45.49713103866922</latitud>
			<altitud>10.85267950617348</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">9.13</distancia>
			<longitud>-73.52223713116189</longitud>
			<latitud>45.49709084856593</latitud>
			<altitud>11.0124882912636</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">9.04</distancia>
			<longitud>-73.52234991554857</longitud>
			<latitud>45.49707188248677</latitud>
			<altitud>11.2869528224454</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.96</distancia>
			<longitud>-73.52246465689912</longitud>
			<latitud>45.4970667619034</latitud>
			<altitud>11.58671043942169</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.60</distancia>
			<longitud>-73.52257497330292</longitud>
			<latitud>45.49706887884435</latitud>
			<altitud>11.90986115905083</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">10.38</distancia>
			<longitud>-73.52270634819736</longitud>
			<latitud>45.49708429025182</latitud>
			<altitud>12.34219501641753</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.94</distancia>
			<longitud>-73.5228181414668</longitud>
			<latitud>45.49710235367237</latitud>
			<altitud>12.67380671699538</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">35.68</distancia>
			<longitud>-73.52325866853936</longitud>
			<latitud>45.49718963092367</latitud>
			<altitud>13.74852292969794</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">36.77</distancia>
			<longitud>-73.52370792006056</longitud>
			<latitud>45.49729047558768</latitud>
			<altitud>14.45862001235767</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">17.08</distancia>
			<longitud>-73.52391208751521</longitud>
			<latitud>45.49734620364882</latitud>
			<altitud>14.59454809661428</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">18.24</distancia>
			<longitud>-73.52412053987065</longitud>
			<latitud>45.49742067345612</latitud>
			<altitud>14.62410873525652</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">17.88</distancia>
			<longitud>-73.52431407874204</longitud>
			<latitud>45.49750708528808</latitud>
			<altitud>14.56466495774735</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">17.81</distancia>
			<longitud>-73.5245005469047</longitud>
			<latitud>45.49759960890318</latitud>
			<altitud>14.47855027500167</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">54.24</distancia>
			<longitud>-73.52503209276861</longitud>
			<latitud>45.49791449574556</latitud>
			<altitud>14.34211518924695</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">62.82</distancia>
			<longitud>-73.52563210985399</longitud>
			<latitud>45.49829171673078</latitud>
			<altitud>14.34370692050259</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">28.06</distancia>
			<longitud>-73.5259028127953</longitud>
			<latitud>45.49845809140326</latitud>
			<altitud>14.27164366444201</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.74</distancia>
			<longitud>-73.52598388852536</longitud>
			<latitud>45.49851240073983</latitud>
			<altitud>14.15843054707944</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">9.00</distancia>
			<longitud>-73.52603900689682</longitud>
			<latitud>45.49858352739389</latitud>
			<altitud>14.04744865419565</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.96</distancia>
			<longitud>-73.52605868094126</longitud>
			<latitud>45.49866288154654</latitud>
			<altitud>13.860810862764</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">8.61</distancia>
			<longitud>-73.52604779754135</longitud>
			<latitud>45.4987398926942</latitud>
			<altitud>13.68857222142309</altitud>
		</tramo>
		<tramo>
			<sector>1</sector>
			<distancia unidades="metros">19.04</distancia>
